/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#57657b",
        "status-error": "#EF4444",
        "inverse-surface": "#2d3133",
        "on-surface": "#191c1e",
        "outline-variant": "#c6c6cd",
        "inverse-primary": "#bec6e0",
        "surface-container-low": "#f2f4f6",
        "on-surface-variant": "#45464d",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#bec6e0",
        "surface-container-highest": "#e0e3e5",
        "on-error-container": "#93000a",
        "surface-container": "#eceef0",
        "status-info": "#3B82F6",
        "tertiary-container": "#002113",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#131b2e",
        "primary-fixed": "#dae2fd",
        "secondary-fixed-dim": "#b9c7e0",
        "on-primary-container": "#7c839b",
        "surface-variant": "#e0e3e5",
        "on-secondary-fixed-variant": "#3a485c",
        "primary-container": "#131b2e",
        "secondary": "#515f74",
        "tertiary-fixed": "#6ffbbe",
        "on-secondary": "#ffffff",
        "primary": "#000000",
        "on-tertiary-fixed-variant": "#005236",
        "surface-tint": "#565e74",
        "secondary-container": "#d5e3fd",
        "surface": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "surface-bright": "#f7f9fb",
        "on-secondary-fixed": "#0d1c2f",
        "risk-medium": "#B45309",
        "status-success": "#10B981",
        "tertiary": "#000000",
        "status-warning": "#F59E0B",
        "risk-high": "#7F1D1D",
        "on-primary-fixed-variant": "#3f465c",
        "surface-dim": "#d8dadc",
        "on-tertiary-fixed": "#002113",
        "risk-low": "#065F46",
        "background": "#f7f9fb",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "outline": "#76777d",
        "on-background": "#191c1e",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-container": "#009668",
        "secondary-fixed": "#d5e3fd",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        "gutter-desktop": "24px",
        "gutter-mobile": "16px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "container-max": "1280px",
        "base": "4px",
      },
      fontFamily: {
        headline: ["Hanken Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
}
